name: Book Volleyball Court Trigger

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"   # 06:00 BRT
    - cron: "0 15 * * *"  # 12:00 BRT
    - cron: "0 21 * * *"  # 18:00 BRT

concurrency:
  group: book-volleyball
  cancel-in-progress: false

jobs:
  run-test:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 horas

    env:
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Test website connectivity
        shell: powershell
        run: |
          Write-Host "================================"
          Write-Host "Testing website connectivity"
          Write-Host "Time: $(Get-Date)"
          Write-Host "================================"

          Write-Host "`nDNS:"
          nslookup reservadeespaco-curitibaemmov.curitiba.pr.gov.br

          Write-Host "`nHTTPS:"
          curl.exe -I -v --connect-timeout 30 https://reservadeespaco-curitibaemmov.curitiba.pr.gov.br/entrar
          exit 0
          
      - name: Restore last notified slots cache
        uses: actions/cache@v4
        with:
          path: lastNotifiedSlots.txt
          key: book-volleyball-last-notified
          restore-keys: |
            book-volleyball-last-notified

      - name: Run Cucumber Scenario every 2 minutes for 6 hours
        shell: powershell
        run: |
          Write-Host "Job started at $(Get-Date)"

          $endTime = (Get-Date).AddHours(5.9)

          $i = 1

          while ((Get-Date) -lt $endTime) {

            Write-Host "=============================="
            Write-Host "Execution $i - $(Get-Date)"
            Write-Host "=============================="

            mvn clean test

            $i++

            if ((Get-Date) -lt $endTime) {
              Write-Host "Sleeping 2 minutes..."
              Start-Sleep -Seconds 120
            }
          }

          Write-Host "Job finished at $(Get-Date)"

      - name: Save last notified slots cache
        uses: actions/cache@v4
        with:
          path: lastNotifiedSlots.txt
          key: book-volleyball-last-notified
